<script lang="ts">
	import { PROVIDERS, PROVIDER_ORDER, type ProviderId } from '$lib/providers';
	import { byok, clearKeys } from '$lib/stores';

	let showKey = $state(false);

	const provider = $derived($byok.provider);
	const info = $derived(PROVIDERS[provider]);
	const selectedModel = $derived($byok.models[provider] ?? info.models[0].id);
	const isCustomModel = $derived(!info.models.some((m) => m.id === selectedModel));
	const key = $derived($byok.keys[provider] ?? '');
	const hasKey = $derived(key.trim().length > 0);

	function setProvider(p: ProviderId) {
		byok.update((s) => ({ ...s, provider: p }));
	}
	function setModel(id: string) {
		byok.update((s) => ({ ...s, models: { ...s.models, [provider]: id } }));
	}
	function setKey(value: string) {
		byok.update((s) => ({ ...s, keys: { ...s.keys, [provider]: value } }));
	}
</script>

<div class="card byok">
	<div class="row head">
		<strong>Bring your own key (RAG)</strong>
		<span class="pill">🔒 stays in your browser</span>
	</div>
	<p class="dim note">
		The answer is generated by calling your chosen provider <em>directly from your browser</em>
		with this key. It is saved only in <code>localStorage</code> and is never sent to the search
		server.
	</p>

	<div class="providers">
		{#each PROVIDER_ORDER as p (p)}
			<button
				class="prov"
				class:active={p === provider}
				onclick={() => setProvider(p)}
				type="button"
			>
				{PROVIDERS[p].label}
				{#if ($byok.keys[p] ?? '').trim()}<span class="dot" title="key set"></span>{/if}
			</button>
		{/each}
	</div>

	<label class="field">
		<span>Model</span>
		<select value={isCustomModel ? '__custom__' : selectedModel} onchange={(e) => {
			const v = (e.target as HTMLSelectElement).value;
			if (v !== '__custom__') setModel(v);
			else setModel('');
		}}>
			{#each info.models as m (m.id)}
				<option value={m.id}>{m.label}{m.free ? ' — free tier' : ''}</option>
			{/each}
			<option value="__custom__">Custom model id…</option>
		</select>
	</label>

	{#if isCustomModel}
		<label class="field">
			<span>Custom model id</span>
			<input
				type="text"
				placeholder="exact model id from the provider"
				value={selectedModel}
				oninput={(e) => setModel((e.target as HTMLInputElement).value)}
			/>
		</label>
	{/if}

	<label class="field">
		<span>API key</span>
		<div class="keyrow">
			<input
				type={showKey ? 'text' : 'password'}
				placeholder={`${info.label} API key`}
				value={key}
				autocomplete="off"
				spellcheck="false"
				oninput={(e) => setKey((e.target as HTMLInputElement).value)}
			/>
			<button class="btn-ghost small" type="button" onclick={() => (showKey = !showKey)}>
				{showKey ? 'hide' : 'show'}
			</button>
		</div>
	</label>

	<div class="row foot">
		<span class="dim">
			{info.keyHint} <a href={info.keyUrl} target="_blank" rel="noreferrer">Get a key ↗</a>
		</span>
		{#if hasKey}
			<button class="btn-ghost small" type="button" onclick={clearKeys}>Clear keys</button>
		{/if}
	</div>
</div>

<style>
	.byok {
		display: flex;
		flex-direction: column;
		gap: 12px;
	}
	.row {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 10px;
	}
	.note {
		margin: 0;
		font-size: 13px;
	}
	.providers {
		display: flex;
		flex-wrap: wrap;
		gap: 8px;
	}
	.prov {
		background: var(--surface-2);
		border: 1px solid var(--border);
		color: var(--text-dim);
		border-radius: 8px;
		padding: 7px 12px;
		font-weight: 600;
		display: inline-flex;
		align-items: center;
		gap: 6px;
	}
	.prov.active {
		border-color: var(--accent);
		color: var(--text);
		box-shadow: 0 0 0 1px var(--accent) inset;
	}
	.dot {
		width: 7px;
		height: 7px;
		border-radius: 50%;
		background: var(--good);
	}
	.field {
		display: flex;
		flex-direction: column;
		gap: 5px;
		font-size: 13px;
		color: var(--text-dim);
	}
	select,
	input {
		background: var(--bg);
		border: 1px solid var(--border);
		color: var(--text);
		border-radius: 8px;
		padding: 9px 11px;
		width: 100%;
	}
	.keyrow {
		display: flex;
		gap: 8px;
	}
	.small {
		padding: 6px 12px;
		font-size: 13px;
		white-space: nowrap;
	}
	.foot {
		font-size: 12px;
	}
</style>
