<script lang="ts">
	import type { ResultItem } from '$lib/api';
	import { PROVIDERS } from '$lib/providers';
	import { byok } from '$lib/stores';
	import { generateAnswer } from '$lib/rag';

	let { query, passages }: { query: string; passages: ResultItem[] } = $props();

	let answer = $state('');
	let error = $state('');
	let loading = $state(false);

	const provider = $derived($byok.provider);
	const info = $derived(PROVIDERS[provider]);
	const model = $derived($byok.models[provider] || info.models[0].id);
	const apiKey = $derived(($byok.keys[provider] ?? '').trim());
	const ready = $derived(apiKey.length > 0 && model.length > 0 && passages.length > 0);
	const MAX_PASSAGES = 5;

	async function run() {
		if (!ready || loading) return;
		loading = true;
		error = '';
		answer = '';
		try {
			answer = await generateAnswer({
				provider,
				model,
				apiKey,
				query,
				passages,
				maxPassages: MAX_PASSAGES
			});
		} catch (e) {
			error = e instanceof Error ? e.message : String(e);
		} finally {
			loading = false;
		}
	}

	// Render inline [n] citations as superscript-ish chips.
	const rendered = $derived(
		answer.split(/(\[\d+\])/g).map((part) => ({
			part,
			isCite: /^\[\d+\]$/.test(part)
		}))
	);
</script>

<div class="card rag">
	<div class="head">
		<strong>RAG answer</strong>
		<span class="dim">grounded in the top {Math.min(MAX_PASSAGES, passages.length)} results</span>
	</div>

	<button class="btn" onclick={run} disabled={!ready || loading}>
		{loading ? 'Generating…' : `Generate answer with ${info.label} · ${model}`}
	</button>

	{#if !apiKey}
		<p class="dim hint">Add your {info.label} key in the panel on the right to enable RAG.</p>
	{:else if passages.length === 0}
		<p class="dim hint">Run a search first, then generate an answer from the results.</p>
	{/if}

	{#if error}
		<div class="error">⚠ {error}</div>
	{/if}

	{#if answer}
		<div class="answer">
			{#each rendered as r}
				{#if r.isCite}<span class="cite">{r.part}</span>{:else}{r.part}{/if}
			{/each}
		</div>
		<p class="dim disclaimer">
			Generated by {info.label} ({model}) in your browser from the retrieved passages. Citations
			[n] refer to the ranked results below.
		</p>
	{/if}
</div>

<style>
	.rag {
		display: flex;
		flex-direction: column;
		gap: 12px;
	}
	.head {
		display: flex;
		justify-content: space-between;
		align-items: baseline;
		gap: 10px;
	}
	.hint {
		margin: 0;
		font-size: 13px;
	}
	.error {
		background: rgba(210, 153, 34, 0.12);
		border: 1px solid var(--warn);
		color: #f0c674;
		border-radius: 8px;
		padding: 10px 12px;
		font-size: 14px;
	}
	.answer {
		background: var(--surface-2);
		border: 1px solid var(--border);
		border-radius: 8px;
		padding: 14px 16px;
		white-space: pre-wrap;
		line-height: 1.6;
	}
	.cite {
		font-family: var(--mono);
		font-size: 12px;
		color: var(--accent-2);
		font-weight: 700;
		padding: 0 1px;
	}
	.disclaimer {
		margin: 0;
		font-size: 12px;
	}
</style>
